name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

# Setup env pipeline
# Create Terraform plan as artifact
# Deploy
# Split into workflow files
